### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by daenamkim** [ascentnetworks/ci-cd-test#1]
# Must be done as soon as possible
- [ ] Setup Jenkins with GitHub.
- [] Write some python samples for TDD.
- [] Write some python test codes.
- [] Setup and run auto test and deploy.
